<!--Should we change this name to the name of the contact person?-->
<?= sprintf($this->translate('Dear %s,'), $company->getName()) . "\n" ?>

<?= $this->translate('You have been registered on the website of Study association GEWIS, with the following information:') . "\n" ?>

    - <?= $this->translate('Name:') ?> <?= $company->getName() . "\n" ?>
    - <?= $this->translate('Email address:') ?> <?= $company->getEmail() . "\n" ?>

<?= $this->translate('You can activate your account on the following link:') . "\n" ?>

<!-- TODO: Change to company /activate when activation page is done
<?= //$this->serverUrl($this->url('user/activate', ['code' => $user->getCode()])) . "\n" ?>
-->
<!-- TODO: Write getCode() function for companies -->
<?= $this->translate('Your activation code is:') ?> <?= //$user->getCode() . "\n" ?>

<?= $this->translate('Best Regards,') . "\n" ?>

<?= $this->translate('WebCommissie GEWIS') ?>
